name: ddshare_fluttify
description: DingTalk Share plugin, developed based on the fluttify engine,Support detection, text sharing, picture sharing, web page sharing.
version: 0.1.1
author: yshye<yshye2013@gmail.com>
homepage: https://github.com/fluttify-project/ddshare_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fluttify.ddshare_fluttify
    pluginClass: DdshareFluttifyPlugin