//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:ddshare_fluttify/src/ios/ios.export.g.dart';
import 'package:ddshare_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_android_dingtalk_share_ddsharemodule_message_DDMediaMessage_IMediaObject on java_lang_Object {
  

  

  @mustCallSuper
  Future<void> serialize(android_os_Bundle var1) {
    kNativeObjectPool.add(var1);
  
    if (!kReleaseMode) {
      debugPrint('serialize::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> unserialize(android_os_Bundle var1) {
    kNativeObjectPool.add(var1);
  
    if (!kReleaseMode) {
      debugPrint('unserialize::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> type() {
  
  
    if (!kReleaseMode) {
      debugPrint('type::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> checkArgs() {
  
  
    if (!kReleaseMode) {
      debugPrint('checkArgs::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getSupportVersion() {
  
  
    if (!kReleaseMode) {
      debugPrint('getSupportVersion::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}